#!/usr/bin/env bash
# Stage 20 - build the Arch Linux ARM aarch64 root filesystem for the uConsole.
#
# Installs the base system plus every Omarchy package that Arch Linux ARM
# already ships for aarch64 (see bin/triage-packages.sh), drops in the kernel
# built by stage 10, and applies the uConsole hardware overlay.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/../../config/build.env"
source "$HERE/../../bin/lib.sh"

step "Stage 20: root filesystem"
require_arm64_emulation
require_file "$OUT_DIR/kernel/kernel.release" "stage 10 has not run - no kernel to install"

ROOTFS="$WORK_DIR/rootfs"
TARBALL="$CACHE_DIR/$(basename "$ALARM_TARBALL")"

# --- base tarball ----------------------------------------------------------
if [[ ! -s "$TARBALL" ]]; then
  info "downloading Arch Linux ARM aarch64 base"
  curl -fL --retry 3 --max-time 1800 "$ALARM_TARBALL" -o "$TARBALL.part"
  mv "$TARBALL.part" "$TARBALL"
fi
info "base tarball: $(du -h "$TARBALL" | cut -f1)"

# --- the package set -------------------------------------------------------
# Everything triaged as available for aarch64. Regenerated each run so the list
# in git always matches what the triage actually found.
TRIAGE="$HERE/../../packages/triage.tsv"
require_file "$TRIAGE" "run bin/triage-packages.sh first"
PKGLIST="$HERE/../../packages/base.packages"
{
  echo "# Generated by stages/20-rootfs/build.sh from packages/triage.tsv."
  echo "# Omarchy packages that Arch Linux ARM already provides for aarch64."
  awk -F'\t' '$2=="alarm"{print $1}' "$TRIAGE" | sort -u
} > "$PKGLIST"
info "$(grep -cvE '^\s*(#|$)' "$PKGLIST") packages from the aarch64 repos"

# --- recovery account password --------------------------------------------
# Generate a per-image password unless one was set explicitly. A published
# default on an image that can run sshd is a genuine vulnerability, and this
# repository is public.
if [[ -z "${DEFAULT_PASS:-}" ]]; then
  DEFAULT_PASS="$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 20)"
  mkdir -p "$OUT_DIR"
  umask 077
  {
    echo "Recovery account for $(basename "${IMG_NAME}").img"
    echo
    echo "  user:     $DEFAULT_USER"
    echo "  password: $DEFAULT_PASS"
    echo
    echo "Generated per-build; not committed and not published anywhere."
    echo "Omarchy creates your real account on first boot - this exists only for"
    echo "recovery (no display, failed provisioning, SSH debugging)."
    echo
    echo "To pick your own instead:  DEFAULT_PASS=... ./build.sh"
  } > "$OUT_DIR/RECOVERY-PASSWORD.txt"
  umask 022
  warn "recovery password generated -> $OUT_DIR/RECOVERY-PASSWORD.txt"
fi
export DEFAULT_PASS

build_image "$IMG_ALARM" "$HERE"

# The rootfs must be built as root (ownership, setuid bits, device nodes) and
# needs mount(2) for the chroot, so this stage runs privileged.
run_in_root "$IMG_ALARM" \
  --privileged \
  -v "$WORK_DIR:/work" \
  -v "$CACHE_DIR:/cache" \
  -v "$OUT_DIR:/out" \
  -v "$HERE/../..:/src:ro" \
  -e "TARBALL=/cache/$(basename "$TARBALL")" \
  -e "DEFAULT_HOSTNAME=$DEFAULT_HOSTNAME" \
  -e "DEFAULT_USER=$DEFAULT_USER" \
  -e "DEFAULT_PASS=$DEFAULT_PASS" \
  -e "DEFAULT_TZ=$DEFAULT_TZ" \
  -e "DEFAULT_LOCALE=$DEFAULT_LOCALE" \
  -e "UC_MODEL=$UC_MODEL" \
  -e "KERNEL_IMAGE_NAME=$KERNEL_IMAGE_NAME" \
  -- bash -euo pipefail /src/stages/20-rootfs/inside.sh

ok "root filesystem ready at $ROOTFS"
